spring: 
  profiles: 
    active: 
    - dev

---
server: 
  port: 8001

mybatis: 
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.entity
  mapper-locations: 
  - classpath:mybatis/mapper/**/*.xml

spring: 
  profiles: dev
  application: 
    name: config-provider-8001
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    dbcp2: 
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

eureka: 
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://eureka01.com:7001/eureka/ #单机版
  instance: 
    instance-id: configprovider8001
    prefer-ip-address: true     #访问路径可以显示IP地址

info: 
  app.name: parent-springcloud
  company.name: www.parent.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

---
server: 
  port: 8001

mybatis: 
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.entity
  mapper-locations: 
  - classpath:mybatis/mapper/**/*.xml

spring: 
  profiles: test
  application: 
    name: config-provider-8001
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    dbcp2: 
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

eureka: 
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://eureka01.com:7001/eureka/ #单机版
  instance: 
    instance-id: configprovider8001
    prefer-ip-address: true     #访问路径可以显示IP地址

info: 
  app.name: parent-springcloud
  company.name: www.parent.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$