spring: 
  profiles: 
    active: 
    - dev

---
server:
  port: 7001
spring: 
  profiles: dev      #开发环境

#####    eureka服务注册地址
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka01.com:5001/eureka/,http://eureka02.com:5002/eureka/,http://eureka03.com:5003/eureka/
    register-with-eureka: true
    fetch-registry: true #是否需要从eureka上获取注册信息
  instance: 
    instance-id: order-7001
    prefer-ip-address: true

#开启Hystrix 服务
feign: 
  hystrix: 
    enabled: true

hystrix: 
  command: 
    default: 
      execution: 
        isolation: 
          strategy: THREAD #线程池隔离 SEMAPHORE为信号量隔离
          thread: 
            timeoutInMilliseconds: 3000 #熔断超时时间
            interruptOnTimeOut: true #超时是否中断

ribbon: 
  ReadTimeout: 5000 #请求处理的超时时间
  ConnectTimeout: 5000 #请求连接超时时间
  MaxAutoRetries: 0 #对当前实例的重试次数
  MaxAutoRetriesNextServer: 1 #切换实例的重试次数 1

info: 
  app.name: order-7001
  company.name: www.scloud.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server:
  port: 7001
spring: 
  profiles: sit      #测试环境

#####    eureka服务注册地址    
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka01.com:5001/eureka/,http://eureka02.com:5002/eureka/,http://eureka03.com:5003/eureka/
    register-with-eureka: true
    fetch-registry: true #是否需要从eureka上获取注册信息
  instance: 
    instance-id: order-7001-sit
    prefer-ip-address: true

#开启Hystrix 服务
feign: 
  hystrix: 
    enabled: true

hystrix: 
  command: 
    default: 
      execution: 
        isolation: 
          strategy: THREAD #线程池隔离 SEMAPHORE为信号量隔离
          thread: 
            timeoutInMilliseconds: 3000 #熔断超时时间
            interruptOnTimeOut: true #超时是否中断

ribbon: 
  ReadTimeout: 5000 #请求处理的超时时间
  ConnectTimeout: 5000 #请求连接超时时间
  MaxAutoRetries: 0 #对当前实例的重试次数
  MaxAutoRetriesNextServer: 1 #切换实例的重试次数 1

info: 
  app.name: order-7001-sit
  company.name: www.scloud.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$